language: csharp
solution: IonHashDotnet.sln
dotnet: 2.1
mono: none
dist: xenial

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive


script:
  - git submodule init
  - git submodule update
  - cd IonHashDotnet.Tests
  - dotnet test -c Release
  - dotnet test
  - cd ..
